server.port=8081
spring.application.name=property-management-system

# Database URL, Username, and Password
spring.datasource.url=jdbc:postgresql://localhost:5432/pms_dev_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
