server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_dev_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

pms:
  pos:
    upload:
      product-image-dir: ${LOCALAPPDATA}\pms-data\pos\product-images
      max-file-size-bytes: 2097152