spring:
  application:
    name: property-management-system
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

app:
  jwt:
    secret: "@SecurelyAndRandomlyGeneratedSecretKeyOfAtLeast32BytesLength@!"
    access-token-validity-ms: 900000
    refresh-token-validity-ms: 604800000